version: '4.31.1'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=quote_service
      - NATS_URL=nats://nats:4222
    volumes:
      - .:/app
    depends_on:
      - postgres
      - nats

    postgres:
      image: postgres:16.3
      ports:
        - '5432:5432'
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: quote_service
      volumes:
        - postgres_data:/var/lib/postgresql/data

    nats:
      image: nats:2.26.0
      ports:
        - '4222:4222'
        - '8222:8222'

  volumes:
    postgres_data: